package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'dslr_interface',
  visibility = ['//visibility:public'],
  srcs = [
    'dslr_interface.cc',
  ],
  hdrs = [
    'dslr_interface.h',
  ],
  deps = [
    '//aos/common/util:phased_loop',
  ],
)
