cc_library(
  name = 'mavlink_serial',
  visibility = ['//visibility:public'],
  srcs = [
    'mavlink_serial.cc',
  ],
  hdrs = [
    'mavlink_serial.h',
  ],
  copts = [
    '-Wno-unused-parameter',
  ],
  deps = [
    '@mavlink_v1//:mavlink_v1'
  ],
)
