cc_binary(
  name = 'ipc_sender',
  visibility = ['//visibility:public'],
  srcs = glob([
    'ipc_sender.cc'
  ]),
)

cc_binary(
  name = 'ipc_receiver',
  visibility = ['//visibility:public'],
  srcs = glob([
    'ipc_receiver.cc'
  ]),
)
