sudo: required
dist: trusty
language: generic

services:
  - docker

install:
  # Setup tools.
  - sudo ./tools/setup_tools.sh
  # Build images.
  - ./server/build.sh
  - ./client/build.sh

script:
  # Test server.
  - ./server/test.sh
  - ./server/run.sh
  # Test client.
  - ./client/test.sh
  # Verify that docs build.
  - ./tools/build_docs.sh
  # Check formatting.
  - ./tools/format.sh --all

after_success:
  # Push to Dockerhub.
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push auvsisuas/interop-server;
    docker push auvsisuas/interop-client;
    fi
