environment:
  global: {}

install:
  - cmd: 'SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH%'
  - cmd: 'python -m pip install pip'
  - cmd: 'python setup.py install'
  - cmd: 'pip install nose'

build_script:
  - cmd: 'setlocal & cd c:\\ & dronekit-sitl --list & endlocal'
  - cmd: 'nosetests tests'

clone_depth: 10
cache:
  - '%CYG_CACHE%'
test: 'off'
branches:
  only:
    - master
