package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'deployment',
  visibility = ['//visibility:public'],
  srcs = [
    'deployment.cc',
  ],
  hdrs = [
    'deployment.h',
  ],
  deps = [
    '//lib/ros:ros',
  ]
)
