cc_library(
  name = 'led_strip',
  visibility = ['//visibility:public'],
  srcs = [
    'led_strip.cc'
  ],
  hdrs = [
    'led_strip.h'
  ],
  deps = [
    '//lib/phased_loop:phased_loop',
    '//lib/ros:ros',
    "@rpi_ws281x//:rpi_ws281x",
  ],
)
