cc_library(
  name = 'context_visitor',
  visibility = ['//visibility:public'],
  srcs = [
    'context_visitor.cc'
  ],
  hdrs = [
    'context_visitor.h'
  ],
  deps = [
    '//src/controls/ground_controls/timeline:timeline_grammar_cc',
    '//lib/rrt_avoidance:rrt_avoidance',
  ],
)


