#!/bin/bash --norc

exec -a arm-linux-gnueabihf-gcov \
  ${BAZEL_OUTPUT_ROOT}external/gcc_linaro_arm_linux_gnueabihf_raspbian_repo/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcov \
  "$@"
