cc_library(
  name = 'ground2drone_visitor',
  visibility = ['//visibility:public'],
  srcs = [
    'ground2drone_visitor.cc'
  ],
  hdrs = [
    'ground2drone_visitor.h'
  ],
  deps = [
    '//src/control/ground_server/timeline:timeline_grammar_cc'
  ],
)
