cc_library(
  name = 'serial_device',
  visibility = ['//visibility:public'],
  hdrs = [
    'serial_device.h'
  ],
  srcs = [
    'serial_device.cc'
  ],
  deps = [
    "//lib/base64_tools:base64_tools",
    "@com_google_protobuf//:protobuf",
    "@boost//:crc",
    "@boost//:detail",
  ],
)
