cc_binary(
  name = 'alarm_trigger_test',
  visibility = ['//visibility:public'],
  srcs = [
    'alarm_trigger_test.cc'
  ],
  deps = [
    '//src/controls:messages_cpp',
    '//lib/ros:ros',
  ],
)
