package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'semaphore',
  visibility = ['//visibility:public'],
  srcs = [
    'semaphore.cc',
  ],
  hdrs = [
    'semaphore.h',
  ],
)
