cc_binary(
  name = "my_test",
  srcs = ["my_test.cc"],
  deps = [
    '//lib/ros:ros',
    '//src/controls:messages_cpp'
  ],
)

cc_binary(
  name = "my_test2",
  srcs = ["my_test2.cc"],
  deps = [
    '//lib/ros:ros',
    '//src/controls:messages_cpp'
  ],
)
