cc_library(
  name = 'serial_device',
  visibility = ['//visibility:public'],
  hdrs = [
    'serial_device.h'
  ],
  srcs = [
    'serial_device.cc'
  ],
  deps = [
    '//src/controls:messages_cpp',
    "@com_google_protobuf//:protobuf",
  ],
)
